### Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Andressa",
    "email": "andressa@gmail.com",
    "password": "andressa123"
}

### Login

POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "andressa@gmail.com",
    "password": "andressa123"
}

### AddPost
POST http://localhost:3003/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhmNWYzZWI5LWY0YzktNDc0Ni04OWFkLTczZjJkMmNiY2VlNCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjM5NzE5OTksImV4cCI6MTY2Mzk3NTU5OX0.RtS6TkWKbDyvgPH0tZKdWGVaZqupscglK6O9AaltwW4
Content-Type: application/json

{
    "content": "Primeiro Post!!!"
}
