### AddCompetition
POST http://localhost:3003/competitions/add
Content-Type: application/json

{
    "name": "Final 100m rasos",
    "modality": "100 metros rasos",
    "unit": "s"
}

### ChangeStatus
PUT http://localhost:3003/competitions/cc4e61d9-edfb-42d7-bbf9-86aab7ae27a6
Content-Type: application/json

{
    "newStatus": "Encerrada"
}

### AddResult
POST http://localhost:3003/results/add 
Content-Type: application/json

{
    "competition": "Quartas de final 100m rasos",
    "modality": "100 metros rasos",
    "athlete": "ANDRA",
    "value": 15.1
}

### GetRanking
GET http://localhost:3003/results/ranking
Content-Type: application/json

{
    "competition": "Classificatória 100m rasos",
    "modality": "100 metros rasos"
}