### AddCompetition
POST http://localhost:3003/competitions/add
Content-Type: application/json

{
    "name": "Quartas de final 100m rasos",
    "modality": "Lançamento de dardos",
    "unit": "m"
}

### ChangeStatus
PUT http://localhost:3003/competitions/cc4e61d9-edfb-42d7-bbf9-86aab7ae27a6
Content-Type: application/json

{
    "newStatus": "Em andamento"
}

### AddResult
POST http://localhost:3003/results/add 
Content-Type: application/json

{
    "competition": "Quartas de final lançamento de dardos",
    "modality": "Lançamento de dardos",
    "athlete": "TESTE 2",
    "value": 230.0
}

### GetRanking
GET http://localhost:3003/results/ranking
Content-Type: application/json

{
    "competition": "Classificatória lançamento de dardos",
    "modality": "Lançamento de dardos"
}